SIM_LENGTH = 100

INIT_POPS: int = 50
INIT_LABOUR_RATIO: float = 0.8
INIT_FUNDS_PER_POP: float = 5.00

EMPLOYMENT_RATE: float = 0.9
SAVINGS_RATE: float = 0.5

NUM_MARKET_TYPES: int = 3

TYPE_LABOUR: int = 0
TYPE_PRODUCE: int = 1
TYPE_SERVICES: int = 2

DICT_MARKET_TYPES = {
    TYPE_LABOUR: "Labour",
    TYPE_PRODUCE: "Produce",
    TYPE_SERVICES: "Services"
}

DICT_INIT_AVG_PRICES = {
    TYPE_LABOUR: 5.00,
    TYPE_PRODUCE: 1.00,
    TYPE_SERVICES: 1.00
}

INIT_PRICE_MAX_SPREAD = 0.1

DECISION_ID_INDEX = 0
DECISION_GOOD_TYPE_INDEX = 1
DECISION_FIRM_EXISTS_INDEX = 2
DECISION_PRICE_INDEX = 3