SIM_LENGTH = 100

INIT_POPS: int = 50

NUM_MARKET_TYPES: int = 3

TYPE_LABOUR: int = 0
TYPE_PRODUCE: int = 1
TYPE_SERVICES: int = 2

DICT_MARKET_TYPES = {
    TYPE_LABOUR: "Labour",
    TYPE_PRODUCE: "Produce",
    TYPE_SERVICES: "Services"
}